import type { Counterparty, Transaction, DashboardStats } from "./types";

export const mockCounterparties: Counterparty[] = [
  {
    id: "CP-001",
    legalName: "Accra Gold Trading Ltd",
    registrationNumber: "GH-2024-78542",
    jurisdiction: "GH",
    address: "14 Independence Avenue, Accra, Ghana",
    contactEmail: "compliance@accragold.com",
    contactPhone: "+233 24 555 1234",
    sourceTypes: ["ASM", "LSM"],
    ubos: [
      {
        id: "UBO-001",
        name: "Kwame Asante",
        nationality: "GH",
        ownershipPercentage: 65,
        isPEP: false,
      },
      {
        id: "UBO-002",
        name: "Ama Mensah",
        nationality: "GH",
        ownershipPercentage: 35,
        isPEP: false,
      },
    ],
    documents: [
      {
        id: "DOC-001",
        type: "BUSINESS_LICENSE",
        name: "business_license_2024.pdf",
        uploadedAt: new Date("2024-12-15"),
        status: "VERIFIED",
      },
      {
        id: "DOC-002",
        type: "AML_POLICY",
        name: "aml_policy_v3.pdf",
        uploadedAt: new Date("2024-12-15"),
        status: "VERIFIED",
      },
      {
        id: "DOC-003",
        type: "UBO_DECLARATION",
        name: "ubo_declaration.pdf",
        uploadedAt: new Date("2024-12-15"),
        status: "VERIFIED",
      },
    ],
    screening: {
      sanctionsStatus: "CLEAR",
      unList: "CLEAR",
      euList: "CLEAR",
      ofacList: "CLEAR",
      pepStatus: false,
      adverseMediaHits: 0,
      preliminaryScore: 24,
      riskLevel: "LOW",
      lastChecked: new Date("2024-12-20"),
    },
    status: "PENDING_REVIEW",
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-20"),
    submittedBy: "John Doe",
  },
  {
    id: "CP-002",
    legalName: "Swiss Precious Metals AG",
    registrationNumber: "CHE-123.456.789",
    jurisdiction: "CH",
    address: "Bahnhofstrasse 45, 8001 Zurich, Switzerland",
    contactEmail: "kyc@swissprec.ch",
    contactPhone: "+41 44 555 1234",
    sourceTypes: ["LSM", "RECYCLED"],
    ubos: [
      {
        id: "UBO-003",
        name: "Hans Mueller",
        nationality: "CH",
        ownershipPercentage: 100,
        isPEP: false,
      },
    ],
    documents: [
      {
        id: "DOC-004",
        type: "BUSINESS_LICENSE",
        name: "handelsregister.pdf",
        uploadedAt: new Date("2024-12-10"),
        status: "VERIFIED",
      },
      {
        id: "DOC-005",
        type: "AML_POLICY",
        name: "compliance_manual.pdf",
        uploadedAt: new Date("2024-12-10"),
        status: "VERIFIED",
      },
    ],
    screening: {
      sanctionsStatus: "CLEAR",
      unList: "CLEAR",
      euList: "CLEAR",
      ofacList: "CLEAR",
      pepStatus: false,
      adverseMediaHits: 0,
      preliminaryScore: 12,
      riskLevel: "LOW",
      lastChecked: new Date("2024-12-18"),
    },
    status: "APPROVED",
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-18"),
    submittedBy: "Jane Smith",
  },
  {
    id: "CP-003",
    legalName: "DRC Mining Cooperative SARL",
    registrationNumber: "CD-2023-45678",
    jurisdiction: "CD",
    address: "Avenue Lumumba 78, Kinshasa, DRC",
    contactEmail: "info@drcmining.cd",
    contactPhone: "+243 81 555 6789",
    sourceTypes: ["ASM"],
    ubos: [
      {
        id: "UBO-004",
        name: "Jean-Pierre Kabila",
        nationality: "CD",
        ownershipPercentage: 40,
        isPEP: true,
        position: "Former Regional Governor",
      },
      {
        id: "UBO-005",
        name: "Marie Tshisekedi",
        nationality: "CD",
        ownershipPercentage: 60,
        isPEP: false,
      },
    ],
    documents: [
      {
        id: "DOC-006",
        type: "BUSINESS_LICENSE",
        name: "licence_commerciale.pdf",
        uploadedAt: new Date("2024-12-05"),
        status: "PENDING",
      },
    ],
    screening: {
      sanctionsStatus: "CLEAR",
      unList: "CLEAR",
      euList: "CLEAR",
      ofacList: "CLEAR",
      pepStatus: true,
      adverseMediaHits: 3,
      preliminaryScore: 68,
      riskLevel: "HIGH",
      lastChecked: new Date("2024-12-19"),
    },
    status: "PENDING_REVIEW",
    createdAt: new Date("2024-12-05"),
    updatedAt: new Date("2024-12-19"),
    submittedBy: "John Doe",
  },
  {
    id: "CP-004",
    legalName: "Dubai Gold Souq DMCC",
    registrationNumber: "DMCC-789456",
    jurisdiction: "AE",
    address: "Gold Tower, DMCC Free Zone, Dubai, UAE",
    contactEmail: "compliance@dubaigoldsouq.ae",
    contactPhone: "+971 4 555 7890",
    sourceTypes: ["RECYCLED"],
    ubos: [
      {
        id: "UBO-006",
        name: "Ahmed Al Maktoum",
        nationality: "AE",
        ownershipPercentage: 100,
        isPEP: false,
      },
    ],
    documents: [
      {
        id: "DOC-007",
        type: "BUSINESS_LICENSE",
        name: "dmcc_license.pdf",
        uploadedAt: new Date("2024-12-08"),
        status: "VERIFIED",
      },
      {
        id: "DOC-008",
        type: "AML_POLICY",
        name: "aml_framework.pdf",
        uploadedAt: new Date("2024-12-08"),
        status: "VERIFIED",
      },
      {
        id: "DOC-009",
        type: "UBO_DECLARATION",
        name: "ubo_form.pdf",
        uploadedAt: new Date("2024-12-08"),
        status: "VERIFIED",
      },
    ],
    screening: {
      sanctionsStatus: "CLEAR",
      unList: "CLEAR",
      euList: "CLEAR",
      ofacList: "CLEAR",
      pepStatus: false,
      adverseMediaHits: 1,
      preliminaryScore: 35,
      riskLevel: "MEDIUM",
      lastChecked: new Date("2024-12-17"),
    },
    status: "PENDING_REVIEW",
    createdAt: new Date("2024-12-08"),
    updatedAt: new Date("2024-12-17"),
    submittedBy: "Jane Smith",
  },
  {
    id: "CP-005",
    legalName: "Sanctioned Entity LLC",
    registrationNumber: "RU-2020-99999",
    jurisdiction: "RU",
    address: "Prospekt Mira 12, Moscow, Russia",
    contactEmail: "contact@sanctioned.ru",
    contactPhone: "+7 495 555 0000",
    sourceTypes: ["LSM"],
    ubos: [
      {
        id: "UBO-007",
        name: "Igor Petrov",
        nationality: "RU",
        ownershipPercentage: 100,
        isPEP: true,
        position: "Government Official",
      },
    ],
    documents: [],
    screening: {
      sanctionsStatus: "HIT",
      unList: "CLEAR",
      euList: "HIT",
      ofacList: "HIT",
      pepStatus: true,
      adverseMediaHits: 15,
      preliminaryScore: 100,
      riskLevel: "HIGH",
      lastChecked: new Date("2024-12-20"),
    },
    status: "BLOCKED",
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-20"),
    submittedBy: "John Doe",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "TXN-001",
    lotId: "LOT-2024-001",
    counterpartyId: "CP-002",
    counterpartyName: "Swiss Precious Metals AG",
    weightKg: 125.5,
    purityPercent: 99.5,
    status: "SETTLED",
    valueUSD: 9876543,
    createdAt: new Date("2024-12-18"),
  },
  {
    id: "TXN-002",
    lotId: "LOT-2024-002",
    counterpartyId: "CP-002",
    counterpartyName: "Swiss Precious Metals AG",
    weightKg: 78.2,
    purityPercent: 99.9,
    status: "ASSAYED",
    valueUSD: 6154321,
    createdAt: new Date("2024-12-19"),
  },
  {
    id: "TXN-003",
    lotId: "LOT-2024-003",
    counterpartyId: "CP-004",
    counterpartyName: "Dubai Gold Souq DMCC",
    weightKg: 45.0,
    purityPercent: 99.5,
    status: "IN_TRANSIT",
    valueUSD: 3543210,
    createdAt: new Date("2024-12-20"),
  },
  {
    id: "TXN-004",
    lotId: "LOT-2024-004",
    counterpartyId: "CP-001",
    counterpartyName: "Accra Gold Trading Ltd",
    weightKg: 32.8,
    purityPercent: 97.5,
    status: "RECEIVED",
    valueUSD: 2521000,
    createdAt: new Date("2024-12-20"),
  },
];

export const mockDashboardStats: DashboardStats = {
  activeCounterparties: 12,
  pendingPOs: 5,
  goldInTransitKg: 245.8,
  monthlyAcquiredKg: 1248.5,
  activeCounterpartiesTrend: 8.3,
  pendingPOsTrend: -12.5,
  goldInTransitTrend: 15.2,
  monthlyAcquiredTrend: 5.7,
};

export const countryNames: Record<string, string> = {
  GH: "Ghana",
  CH: "Switzerland",
  CD: "DRC",
  AE: "UAE",
  RU: "Russia",
  ZA: "South Africa",
  AU: "Australia",
  US: "United States",
  GB: "United Kingdom",
  CA: "Canada",
  ML: "Mali",
  BF: "Burkina Faso",
  TZ: "Tanzania",
  PE: "Peru",
  CO: "Colombia",
};

export const jurisdictions = [
  { code: "GH", name: "Ghana", riskLevel: "MEDIUM" as const },
  { code: "CH", name: "Switzerland", riskLevel: "LOW" as const },
  { code: "CD", name: "Democratic Republic of Congo", riskLevel: "HIGH" as const },
  { code: "AE", name: "United Arab Emirates", riskLevel: "LOW" as const },
  { code: "ZA", name: "South Africa", riskLevel: "LOW" as const },
  { code: "AU", name: "Australia", riskLevel: "LOW" as const },
  { code: "ML", name: "Mali", riskLevel: "HIGH" as const },
  { code: "BF", name: "Burkina Faso", riskLevel: "HIGH" as const },
  { code: "TZ", name: "Tanzania", riskLevel: "MEDIUM" as const },
  { code: "PE", name: "Peru", riskLevel: "MEDIUM" as const },
];
